2016-03-26 12:56:33 [5121] [INFO] Starting gunicorn 17.5
2016-03-26 12:56:33 [5121] [INFO] Listening at: http://0.0.0.0:8000 (5121)
2016-03-26 12:56:33 [5121] [INFO] Using worker: sync
2016-03-26 12:56:33 [5126] [INFO] Booting worker with pid: 5126
2016-03-26 12:56:33 [5127] [INFO] Booting worker with pid: 5127
2016-03-26 13:07:10 [5121] [INFO] Handling signal: term
2016-03-26 09:07:10 [5126] [INFO] Worker exiting (pid: 5126)
2016-03-26 09:07:10 [5127] [INFO] Worker exiting (pid: 5127)
2016-03-26 13:07:10 [5121] [INFO] Shutting down: Master
2016-03-26 13:07:11 [5285] [INFO] Starting gunicorn 17.5
2016-03-26 13:07:11 [5285] [INFO] Listening at: http://0.0.0.0:8000 (5285)
2016-03-26 13:07:11 [5285] [INFO] Using worker: sync
2016-03-26 13:07:11 [5294] [INFO] Booting worker with pid: 5294
2016-03-26 13:07:11 [5295] [INFO] Booting worker with pid: 5295
2016-03-26 13:58:42 [5285] [INFO] Handling signal: term
2016-03-26 09:58:42 [5294] [INFO] Worker exiting (pid: 5294)
2016-03-26 09:58:42 [5295] [INFO] Worker exiting (pid: 5295)
2016-03-26 13:58:42 [5285] [INFO] Shutting down: Master
2016-03-26 13:58:43 [6677] [INFO] Starting gunicorn 17.5
2016-03-26 13:58:43 [6677] [INFO] Listening at: http://0.0.0.0:8000 (6677)
2016-03-26 13:58:43 [6677] [INFO] Using worker: sync
2016-03-26 13:58:43 [6682] [INFO] Booting worker with pid: 6682
2016-03-26 13:58:43 [6683] [INFO] Booting worker with pid: 6683
2016-03-26 14:11:21 [6677] [INFO] Handling signal: term
2016-03-26 14:11:21 [6682] [INFO] Worker exiting (pid: 6682)
2016-03-26 14:11:21 [6683] [INFO] Worker exiting (pid: 6683)
2016-03-26 14:11:21 [6677] [INFO] Shutting down: Master
2016-03-26 17:39:07 [1645] [INFO] Starting gunicorn 17.5
2016-03-26 17:39:07 [1645] [INFO] Listening at: http://0.0.0.0:8000 (1645)
2016-03-26 17:39:07 [1645] [INFO] Using worker: sync
2016-03-26 17:39:07 [1669] [INFO] Booting worker with pid: 1669
2016-03-26 17:39:07 [1671] [INFO] Booting worker with pid: 1671
2016-03-27 01:36:30 [1645] [INFO] Handling signal: term
Exception SystemExit: 0 in <module 'threading' from '/usr/lib/python2.7/threading.pyc'> ignored
Exception SystemExit: 0 in <module 'threading' from '/usr/lib/python2.7/threading.pyc'> ignored
Exception SystemExit: 0 in <module 'threading' from '/usr/lib/python2.7/threading.pyc'> ignored
Exception SystemExit: SystemExit(0,) in <module 'threading' from '/usr/lib/python2.7/threading.pyc'> ignored
2016-03-27 01:36:31 [1645] [INFO] Shutting down: Master
2016-03-27 23:17:52 [1661] [INFO] Starting gunicorn 17.5
2016-03-27 23:17:52 [1661] [INFO] Listening at: http://0.0.0.0:8000 (1661)
2016-03-27 23:17:52 [1661] [INFO] Using worker: sync
2016-03-27 23:17:52 [1705] [INFO] Booting worker with pid: 1705
2016-03-27 23:17:52 [1717] [INFO] Booting worker with pid: 1717
2016-03-28 00:07:59 [1661] [INFO] Handling signal: term
2016-03-28 00:07:59 [1705] [INFO] Worker exiting (pid: 1705)
2016-03-28 00:07:59 [1717] [INFO] Worker exiting (pid: 1717)
2016-03-28 00:07:59 [1661] [INFO] Shutting down: Master
2016-03-30 09:52:07 [1657] [INFO] Starting gunicorn 17.5
2016-03-30 09:52:07 [1657] [INFO] Listening at: http://0.0.0.0:8000 (1657)
2016-03-30 09:52:07 [1657] [INFO] Using worker: sync
2016-03-30 09:52:07 [1686] [INFO] Booting worker with pid: 1686
2016-03-30 09:52:07 [1696] [INFO] Booting worker with pid: 1696
2016-03-30 10:06:33 [1657] [INFO] Handling signal: term
Exception SystemExitException SystemExit: : 0 in 0 in <module 'threading' from '/usr/lib/python2.7/threading.pyc'> ignored
<module 'threading' from '/usr/lib/python2.7/threading.pyc'> ignored
Exception SystemExit: 0 in <module 'threading' from '/usr/lib/python2.7/threading.pyc'> ignored
Exception SystemExit: 0 in <module 'threading' from '/usr/lib/python2.7/threading.pyc'> ignored
2016-03-30 10:06:34 [1657] [INFO] Shutting down: Master
2016-03-30 10:06:36 [3999] [INFO] Starting gunicorn 17.5
2016-03-30 10:06:36 [3999] [INFO] Listening at: http://0.0.0.0:8000 (3999)
2016-03-30 10:06:36 [3999] [INFO] Using worker: sync
2016-03-30 10:06:36 [4004] [INFO] Booting worker with pid: 4004
2016-03-30 10:06:36 [4005] [INFO] Booting worker with pid: 4005
2016-03-30 10:07:27 [4004] [ERROR] Error handling request
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/gunicorn/workers/sync.py", line 126, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/wsgi.py", line 187, in __call__
    self.load_middleware()
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 46, in load_middleware
    for middleware_path in settings.MIDDLEWARE_CLASSES:
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 54, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 49, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 128, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/home/box/web/ask/ask/settings.py", line 29, in <module>
    TEMPLATE_DIRS (
NameError: name 'TEMPLATE_DIRS' is not defined
2016-03-30 10:08:28 [4005] [ERROR] Error handling request
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/gunicorn/workers/sync.py", line 126, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/wsgi.py", line 187, in __call__
    self.load_middleware()
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 46, in load_middleware
    for middleware_path in settings.MIDDLEWARE_CLASSES:
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 54, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 49, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 128, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/home/box/web/ask/ask/settings.py", line 29, in <module>
    TEMPLATE_DIRS (
NameError: name 'TEMPLATE_DIRS' is not defined
2016-03-30 10:11:35 [4005] [ERROR] Error handling request
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/gunicorn/workers/sync.py", line 126, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/wsgi.py", line 187, in __call__
    self.load_middleware()
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 46, in load_middleware
    for middleware_path in settings.MIDDLEWARE_CLASSES:
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 54, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 49, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 128, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/home/box/web/ask/ask/settings.py", line 29, in <module>
    TEMPLATE_DIRS (
NameError: name 'TEMPLATE_DIRS' is not defined
2016-03-30 10:12:07 [3999] [INFO] Handling signal: term
2016-03-30 10:12:07 [4004] [INFO] Worker exiting (pid: 4004)
2016-03-30 10:12:07 [4005] [INFO] Worker exiting (pid: 4005)
2016-03-30 10:12:07 [3999] [INFO] Shutting down: Master
2016-03-30 10:12:08 [4868] [INFO] Starting gunicorn 17.5
2016-03-30 10:12:08 [4868] [INFO] Listening at: http://0.0.0.0:8000 (4868)
2016-03-30 10:12:08 [4868] [INFO] Using worker: sync
2016-03-30 10:12:08 [4876] [INFO] Booting worker with pid: 4876
2016-03-30 10:12:08 [4877] [INFO] Booting worker with pid: 4877
2016-03-30 10:12:12 [4876] [ERROR] Error handling request
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/gunicorn/workers/sync.py", line 126, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/wsgi.py", line 187, in __call__
    self.load_middleware()
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 46, in load_middleware
    for middleware_path in settings.MIDDLEWARE_CLASSES:
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 54, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 49, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 128, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/home/box/web/ask/ask/settings.py", line 29, in <module>
    TEMPLATE_DIRS (
NameError: name 'TEMPLATE_DIRS' is not defined
2016-03-30 10:12:18 [4877] [ERROR] Error handling request
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/gunicorn/workers/sync.py", line 126, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/wsgi.py", line 187, in __call__
    self.load_middleware()
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 46, in load_middleware
    for middleware_path in settings.MIDDLEWARE_CLASSES:
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 54, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 49, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 128, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/home/box/web/ask/ask/settings.py", line 29, in <module>
    TEMPLATE_DIRS (
NameError: name 'TEMPLATE_DIRS' is not defined
2016-03-30 10:15:31 [4868] [INFO] Handling signal: term
2016-03-30 10:15:31 [4876] [INFO] Worker exiting (pid: 4876)
2016-03-30 10:15:31 [4877] [INFO] Worker exiting (pid: 4877)
2016-03-30 10:15:32 [4868] [INFO] Shutting down: Master
2016-03-30 10:15:32 [5750] [INFO] Starting gunicorn 17.5
2016-03-30 10:15:32 [5750] [INFO] Listening at: http://0.0.0.0:8000 (5750)
2016-03-30 10:15:32 [5750] [INFO] Using worker: sync
2016-03-30 10:15:32 [5755] [INFO] Booting worker with pid: 5755
2016-03-30 10:15:32 [5756] [INFO] Booting worker with pid: 5756
2016-03-30 10:18:37 [5750] [INFO] Handling signal: term
2016-03-30 10:18:37 [5755] [INFO] Worker exiting (pid: 5755)
2016-03-30 10:18:37 [5756] [INFO] Worker exiting (pid: 5756)
2016-03-30 10:18:38 [5750] [INFO] Shutting down: Master
2016-03-30 10:20:12 [6822] [INFO] Starting gunicorn 17.5
2016-03-30 10:20:12 [6822] [INFO] Listening at: http://0.0.0.0:8000 (6822)
2016-03-30 10:20:12 [6822] [INFO] Using worker: sync
2016-03-30 10:20:12 [6827] [INFO] Booting worker with pid: 6827
2016-03-30 10:20:12 [6828] [INFO] Booting worker with pid: 6828
2016-03-30 10:20:37 [6827] [ERROR] Error handling request
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/gunicorn/workers/sync.py", line 126, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/wsgi.py", line 187, in __call__
    self.load_middleware()
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 46, in load_middleware
    for middleware_path in settings.MIDDLEWARE_CLASSES:
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 54, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 49, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 128, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/home/box/web/ask/ask/settings.py", line 29, in <module>
    TEMPLATE_DIRS (
NameError: name 'TEMPLATE_DIRS' is not defined
2016-03-30 10:20:59 [6828] [ERROR] Error handling request
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/gunicorn/workers/sync.py", line 126, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/wsgi.py", line 187, in __call__
    self.load_middleware()
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 46, in load_middleware
    for middleware_path in settings.MIDDLEWARE_CLASSES:
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 54, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 49, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 128, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/home/box/web/ask/ask/settings.py", line 29, in <module>
    TEMPLATE_DIRS (
NameError: name 'TEMPLATE_DIRS' is not defined
2016-03-30 10:21:05 [6827] [ERROR] Error handling request
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/gunicorn/workers/sync.py", line 126, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/wsgi.py", line 187, in __call__
    self.load_middleware()
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 46, in load_middleware
    for middleware_path in settings.MIDDLEWARE_CLASSES:
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 54, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 49, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 128, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/home/box/web/ask/ask/settings.py", line 29, in <module>
    TEMPLATE_DIRS (
NameError: name 'TEMPLATE_DIRS' is not defined
2016-03-30 10:21:14 [6827] [ERROR] Error handling request
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/gunicorn/workers/sync.py", line 126, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/wsgi.py", line 187, in __call__
    self.load_middleware()
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 46, in load_middleware
    for middleware_path in settings.MIDDLEWARE_CLASSES:
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 54, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 49, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 128, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/home/box/web/ask/ask/settings.py", line 29, in <module>
    TEMPLATE_DIRS (
NameError: name 'TEMPLATE_DIRS' is not defined
2016-03-30 10:27:10 [6822] [INFO] Handling signal: term
2016-03-30 10:27:10 [6827] [INFO] Worker exiting (pid: 6827)
2016-03-30 10:27:10 [6828] [INFO] Worker exiting (pid: 6828)
2016-03-30 10:27:10 [6822] [INFO] Shutting down: Master
2016-03-30 10:28:31 [1648] [INFO] Starting gunicorn 17.5
2016-03-30 10:28:31 [1648] [INFO] Listening at: http://0.0.0.0:8000 (1648)
2016-03-30 10:28:31 [1648] [INFO] Using worker: sync
2016-03-30 10:28:31 [1656] [INFO] Booting worker with pid: 1656
2016-03-30 10:28:31 [1663] [INFO] Booting worker with pid: 1663
2016-03-30 11:40:10 [1648] [INFO] Handling signal: term
2016-03-30 11:40:10 [1663] [INFO] Worker exiting (pid: 1663)
2016-03-30 11:40:10 [1656] [INFO] Worker exiting (pid: 1656)
2016-03-30 11:40:10 [1648] [INFO] Shutting down: Master
2016-03-30 15:20:19 [1589] [INFO] Starting gunicorn 17.5
2016-03-30 15:20:19 [1589] [INFO] Listening at: http://0.0.0.0:8000 (1589)
2016-03-30 15:20:19 [1589] [INFO] Using worker: sync
2016-03-30 15:20:19 [1635] [INFO] Booting worker with pid: 1635
2016-03-30 15:20:19 [1644] [INFO] Booting worker with pid: 1644
2016-03-30 15:29:16 [1589] [INFO] Handling signal: term
2016-03-30 15:29:16 [1635] [INFO] Worker exiting (pid: 1635)
2016-03-30 15:29:16 [1644] [INFO] Worker exiting (pid: 1644)
2016-03-30 15:29:17 [1589] [INFO] Shutting down: Master
2016-03-30 15:30:34 [1655] [INFO] Starting gunicorn 17.5
2016-03-30 15:30:34 [1655] [INFO] Listening at: http://0.0.0.0:8000 (1655)
2016-03-30 15:30:34 [1655] [INFO] Using worker: sync
2016-03-30 15:30:34 [1673] [INFO] Booting worker with pid: 1673
2016-03-30 15:30:34 [1679] [INFO] Booting worker with pid: 1679
2016-03-30 15:33:45 [1655] [INFO] Handling signal: term
2016-03-30 15:33:45 [1673] [INFO] Worker exiting (pid: 1673)
2016-03-30 15:33:45 [1679] [INFO] Worker exiting (pid: 1679)
2016-03-30 15:33:45 [1655] [INFO] Shutting down: Master
2016-03-30 15:33:46 [2949] [INFO] Starting gunicorn 17.5
2016-03-30 15:33:46 [2949] [INFO] Listening at: http://0.0.0.0:8000 (2949)
2016-03-30 15:33:46 [2949] [INFO] Using worker: sync
2016-03-30 15:33:46 [2954] [INFO] Booting worker with pid: 2954
2016-03-30 15:33:46 [2955] [INFO] Booting worker with pid: 2955
2016-03-30 15:34:31 [2955] [ERROR] Error handling request
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/gunicorn/workers/sync.py", line 126, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/wsgi.py", line 187, in __call__
    self.load_middleware()
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 46, in load_middleware
    for middleware_path in settings.MIDDLEWARE_CLASSES:
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 54, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 49, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 128, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/home/box/web/ask/ask/settings.py", line 29, in <module>
    TEMPLATE_DIRS (
NameError: name 'TEMPLATE_DIRS' is not defined
2016-03-30 15:38:36 [2949] [INFO] Handling signal: term
2016-03-30 15:38:36 [2954] [INFO] Worker exiting (pid: 2954)
2016-03-30 15:38:36 [2955] [INFO] Worker exiting (pid: 2955)
2016-03-30 15:38:36 [2949] [INFO] Shutting down: Master
2016-03-30 15:39:53 [3152] [INFO] Starting gunicorn 17.5
2016-03-30 15:39:53 [3152] [INFO] Listening at: http://0.0.0.0:8000 (3152)
2016-03-30 15:39:53 [3152] [INFO] Using worker: sync
2016-03-30 15:39:53 [3157] [INFO] Booting worker with pid: 3157
2016-03-30 15:39:53 [3158] [INFO] Booting worker with pid: 3158
2016-03-30 15:40:02 [3157] [ERROR] Error handling request
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/gunicorn/workers/sync.py", line 126, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/wsgi.py", line 187, in __call__
    self.load_middleware()
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 46, in load_middleware
    for middleware_path in settings.MIDDLEWARE_CLASSES:
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 54, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 49, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 128, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/home/box/web/ask/ask/settings.py", line 29, in <module>
    TEMPLATE_DIRS (
NameError: name 'TEMPLATE_DIRS' is not defined
2016-03-30 16:00:11 [3152] [INFO] Handling signal: term
2016-03-30 16:00:11 [3157] [INFO] Worker exiting (pid: 3157)
2016-03-30 16:00:11 [3158] [INFO] Worker exiting (pid: 3158)
2016-03-30 16:00:11 [3152] [INFO] Shutting down: Master
2016-03-30 16:00:11 [3424] [INFO] Starting gunicorn 17.5
2016-03-30 16:00:11 [3424] [INFO] Listening at: http://0.0.0.0:8000 (3424)
2016-03-30 16:00:11 [3424] [INFO] Using worker: sync
2016-03-30 16:00:11 [3429] [INFO] Booting worker with pid: 3429
2016-03-30 16:00:11 [3430] [INFO] Booting worker with pid: 3430
2016-03-30 16:00:54 [3430] [ERROR] Error handling request
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/gunicorn/workers/sync.py", line 126, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/wsgi.py", line 187, in __call__
    self.load_middleware()
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 46, in load_middleware
    for middleware_path in settings.MIDDLEWARE_CLASSES:
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 54, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 49, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 128, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/home/box/web/ask/ask/settings.py", line 29, in <module>
    TEMPLATE_DIRS (
NameError: name 'TEMPLATE_DIRS' is not defined
2016-03-30 16:05:31 [3424] [INFO] Handling signal: term
2016-03-30 16:05:31 [3429] [INFO] Worker exiting (pid: 3429)
2016-03-30 16:05:31 [3430] [INFO] Worker exiting (pid: 3430)
2016-03-30 16:05:31 [3424] [INFO] Shutting down: Master
2016-03-30 16:05:32 [3575] [INFO] Starting gunicorn 17.5
2016-03-30 16:05:32 [3575] [INFO] Listening at: http://0.0.0.0:8000 (3575)
2016-03-30 16:05:32 [3575] [INFO] Using worker: sync
2016-03-30 16:05:32 [3580] [INFO] Booting worker with pid: 3580
2016-03-30 16:05:32 [3581] [INFO] Booting worker with pid: 3581
2016-03-30 16:37:52 [3575] [INFO] Handling signal: term
2016-03-30 12:37:52 [3580] [INFO] Worker exiting (pid: 3580)
2016-03-30 12:37:52 [3581] [INFO] Worker exiting (pid: 3581)
2016-03-30 16:37:53 [3575] [INFO] Shutting down: Master
2016-03-30 16:37:53 [3864] [INFO] Starting gunicorn 17.5
2016-03-30 16:37:53 [3864] [INFO] Listening at: http://0.0.0.0:8000 (3864)
2016-03-30 16:37:53 [3864] [INFO] Using worker: sync
2016-03-30 16:37:53 [3869] [INFO] Booting worker with pid: 3869
2016-03-30 16:37:53 [3870] [INFO] Booting worker with pid: 3870
2016-03-30 16:46:46 [3864] [INFO] Handling signal: term
2016-03-30 12:46:46 [3869] [INFO] Worker exiting (pid: 3869)
2016-03-30 12:46:46 [3870] [INFO] Worker exiting (pid: 3870)
2016-03-30 16:46:46 [3864] [INFO] Shutting down: Master
2016-03-30 16:46:47 [3984] [INFO] Starting gunicorn 17.5
2016-03-30 16:46:47 [3984] [INFO] Listening at: http://0.0.0.0:8000 (3984)
2016-03-30 16:46:47 [3984] [INFO] Using worker: sync
2016-03-30 16:46:47 [3989] [INFO] Booting worker with pid: 3989
2016-03-30 16:46:47 [3990] [INFO] Booting worker with pid: 3990
2016-03-30 16:49:13 [3984] [INFO] Handling signal: term
2016-03-30 12:49:13 [3989] [INFO] Worker exiting (pid: 3989)
2016-03-30 12:49:13 [3990] [INFO] Worker exiting (pid: 3990)
2016-03-30 16:49:13 [3984] [INFO] Shutting down: Master
2016-03-30 16:49:14 [4085] [INFO] Starting gunicorn 17.5
2016-03-30 16:49:14 [4085] [INFO] Listening at: http://0.0.0.0:8000 (4085)
2016-03-30 16:49:14 [4085] [INFO] Using worker: sync
2016-03-30 16:49:14 [4090] [INFO] Booting worker with pid: 4090
2016-03-30 16:49:14 [4091] [INFO] Booting worker with pid: 4091
